In [ ]:
import numpy as np

In [ ]:
one_d_arr = np.array([1,2,3,4,5,6])

In [ ]:
one_d_arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
two_d_arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
two_d_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.zeros((2, 3))     # all zeros
np.ones((2, 3))      # all ones
np.full((2, 3), 7)  # all sevens
np.empty((2, 3))     # uninitialized — whatever was already in memory, NOT zero

In [ ]:
arr_zeros = np.zeros((2,5))

In [ ]:
arr_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr_ones = np.ones((3,3))

In [ ]:
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])